# Generated by Django 4.1.7 on 2023-03-30 07:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scambi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(blank=True, max_length=6, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(6)])),
                ('idRichiedente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libri.libri')),
            ],
            options={
                'unique_together': {('libro', 'idRichiedente')},
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroScambi', models.IntegerField(default=0)),
                ('data', models.DateField()),
                ('tempo', models.TimeField()),
                ('utente1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utente1', to=settings.AUTH_USER_MODEL)),
                ('utente2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utente2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utente1', 'utente2')},
            },
        ),
    ]
