# Generated by Django 4.1.7 on 2023-03-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interazioniUtenti', '0002_alter_chat_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='data',
            field=models.DateField(),
        ),
    ]
