# Generated by Django 4.1.7 on 2023-02-23 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(12)])),
            ],
        ),
    ]
