# Generated by Django 4.1.7 on 2023-02-23 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libri',
            name='isbn',
            field=models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(13)]),
        ),
    ]
