# Generated by Django 4.1.7 on 2023-03-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libri', '0004_libri_iduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='libri',
            name='immagine',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
