# Generated by Django 4.1.7 on 2023-03-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libri', '0009_libri_citta'),
    ]

    operations = [
        migrations.AddField(
            model_name='libri',
            name='latitudine',
            field=models.FloatField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libri',
            name='longitudine',
            field=models.FloatField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
