# Generated by Django 4.1.7 on 2023-03-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libri', '0010_libri_latitudine_libri_longitudine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libri',
            name='immagine',
            field=models.ImageField(upload_to=''),
        ),
    ]
