# Generated by Django 4.1.7 on 2023-03-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libri', '0011_alter_libri_immagine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libri',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='images/libri/'),
        ),
    ]
