# Generated by Django 4.1.7 on 2023-03-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libri', '0014_remove_categorie_libro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libri',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='LibriCategorie',
        ),
    ]
