# Generated by Django 4.1.7 on 2023-03-21 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticazione', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilo',
            name='numTopen',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
