# Generated by Django 4.1.7 on 2023-03-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libri', '0007_alter_libri_immagine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libri',
            name='immagine',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
