# Generated by Django 4.1.7 on 2023-03-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libri', '0008_alter_libri_immagine'),
    ]

    operations = [
        migrations.AddField(
            model_name='libri',
            name='citta',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
