# Generated by Django 4.1.7 on 2023-03-16 13:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scambi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6)])),
                ('mittente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mittente', to=settings.AUTH_USER_MODEL)),
                ('ricevente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ricevente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
