# Generated by Django 4.1.7 on 2023-03-16 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libri', '0016_libricategorie_libri_categoria'),
        ('interazioniUtenti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scambi',
            name='libro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libri.libri'),
            preserve_default=False,
        ),
    ]
